name: Build Billiards Tool to EXE

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy mss pyinstaller keyboard pywin32 pygame

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole ballpool.py

    - name: Upload Result
      uses: actions/upload-artifact@v4
      with:
        name: Billiards-Combo-Overlay
        path: dist/ballpool.exe
